services:
  media-sync-api:
    build: .
    pull_policy: never
    container_name: media-sync-api
    ports:
      - "8787:8787"
    volumes:
      - "B:/Video/Projects:/data/projects"
    environment:
      - MEDIA_SYNC_PROJECTS_ROOT=/data/projects
      - MEDIA_SYNC_PORT=8787
    restart: always
